# -*- coding: utf-8 -*-
"""ObjectDetection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12RkKLR1E5P2nCfOGndvD-AMOG-Z248MH
"""

pip install imageai

execution_path=os.getcwd()

from imageai.Detection import ObjectDetection

!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5

!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/resnet50_coco_best_v2.0.1.h5

detector = ObjectDetection()
d=ObjectDetection()
detector.setModelTypeAsYOLOv3()
d.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path, "yolo.h5.5"))
d.setModelPath(os.path.join(execution_path,"resnet50_coco_best_v2.0.1.h5.5"))
detector.loadModel()
d.loadModel()

detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "army.jpg"), output_image_path=os.path.join(execution_path , "army_output.jpg"),minimum_percentage_probability=30)
for eachObject in detections:
    print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
    print("--------------------------------")

det = d.detectObjectsFromImage(input_image=os.path.join(execution_path , "army.jpg"), output_image_path=os.path.join(execution_path , "army_Routput.jpg"),minimum_percentage_probability=30)
for eachObject in det:
    print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
    print("--------------------------------")

















